kind: Cluster 
apiVersion: kind.x-k8s.io/v1alpha4 
nodes: 
# Control planes 
- role: control-plane 
- role: control-plane 
- role: control-plane 
 
# Workers 
- role: worker 
- role: worker 
- role: worker 
 
