kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control planes
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
    labels:
      name: Meli-control-plane-1
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8081
        protocol: TCP
    labels:
      name: Meli-control-plane-2
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8082
        protocol: TCP
    labels:
      name: Meli-control-plane-3

  # Workers
  - role: worker
    labels:
      name: Meli-worker-1
  - role: worker
    labels:
      name: Meli-worker-2
  - role: worker
    labels:
      name: Meli-worker-3
